spring:
  application:
    name: cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MccreeFei/springcloud-demo
          search-paths: config/config-repo

server:
  port: 9005

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
